server:
  port: 9090
  agent:
    url: localhost
    port: 8080

# 공통 경로 설정
common:
  params:
    extract_tmp_dir: /Users/bagjeongmin/Desktop/SpringBoot/api_dir/tmp
    meta_info_path: /Users/bagjeongmin/Desktop/SpringBoot/api_dir/meta

# agent 관련
agent:
  execute:
    cleanup_interval: 60000
    job_check_interval: 5000
    concurrent_job_count: 10
    poll_interval: 3000
    queue_size: 10
    timeout: 10
    connection_count: 100
  batch:
    shell_scripts:
      start_java_batch: /test/startJavaBatch.sh
      start_proc_batch: /test/startProcBatch.sh
      start_multi_batch: /test/startMultiBatch.sh
      start_api_batch: /test/startApiBatch.sh
    paths:
      job_meta_file_path: ${common.params.meta_info_path}
    logs:
      dir_path: /Users/bagjeongmin/Desktop/SpringBoot/api_dir/logs

spring:
  application:
    name: api-collector
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: api_col
    password: 1234

hikari:
  connection-timeout: 1800000
  max-lifetime: 1800000

mybatis:
  mapper-locations: classpath:mappers/**/*.xml
  config-location: classpath:mybatis-config.xml
