### 1. v1/api post 요청
POST http://localhost:9090/v1/api/execute/unload/data
Content-Type: application/json

{
  "JB_ID": "JOB20241202e0f7ae425",
  "JB_DT": "20241212",
  "API_SVC": "StatisticItemList",
  "baseUrl": "https://ecos.bok.or.kr/api/StatisticItemList",
  "pathParams": {
    "key": "J35UU2GFGLGJCZ5L8K4M",
    "type": "json",
    "lang": "kr",
    "start": "1",
    "end": "1000",
    "code": "601Y002"
  },
  "queryParams": {},
  "isPathParam": "true",
  "isQueryParam": "false",
  "keyName": "row",
  "countKeyName": "list_total_count",
  "returnType": "json",
  "DATA_PROVIDER": "한국은행",
  "JDBC_ID": "BATCH_USER",
  "JDBC_PW": "JKxV+LKTS5reMo3Sw35ruj==",
  "JDBC_URL": "jdbc:oracle:thin:@database02.didim365.co:1521:RWK",
  "JDBC_DRIVER": "oracle.jdbc.OracleDriver",
  "CON_CNT": "5"
}